language: go
go_import_path: github.com/weaveworks/ignite
dist: xenial
go:
  - 1.12.9
env:
  - GO111MODULE=on
install:
  - apt-get install dmsetup
  - make bin/amd64/ignite
script:
  - echo script path
