language: go
go_import_path: github.com/weaveworks/ignite
dist: xenial
go:
  - 1.12.9
env:
  - GO111MODULE=on
before_install:
  - sudo apt-get update
  - sudo apt-get install -y dmsetup
  - sudo apt-get install qemu-kvm libvirt-bin virtinst bridge-utils cpu-checker
  - sudo /usr/sbin/kvm-ok
install:
  - make bin/amd64/ignite
script:
  - echo test will be here