language: go
go_import_path: github.com/weaveworks/ignite
dist: xenial
go:
  - 1.12.9
env:
  - GO111MODULE=on
before_install:
  - sudo apt-get update
  - sudo apt-get install -y dmsetup
install:
  - make bin/amd64/ignite
script:
  - echo test will be here